blog/urls.py
from django.urls import path
from . import views
from django.contrib.auth.views import *

app_name = 'blog'
urlpatterns = [
    path('', views.index, name='index'),
    path('post/', views.post_list, name="post_list"),
    path('post/<str:category>/', views.post_list, name='post_list_category'),
    path('post/detail/<int:post_id>/', views.post_detail, name="post_detail"),
    path('post/<int:post_id>/comment/', views.post_comment, name="post_comment"),
    path('post/create/', views.post_create, name="post_create"),
    path('post/edit/<int:post_id>/', views.post_edit, name='post_edit'),
    path('post/delete/<int:post_id>/', views.post_delete, name="post_delete"),
    path('image/delete/<int:image_id>/', views.image_delete, name="image_delete"),
    path('ticket/', views.ticket, name="ticket"),
    path('search/', views.post_search, name="post_search"),
    path('profile/', views.profile, name='profile'),
    # path('login/', views.user_login, name='login'),
    path('login/', LoginView.as_view(), name='login'),
    path('logout/', LogoutView.as_view(), name='logout'),
    # path('logout/', views.logout_view, name='logout'),
    path('password_change/', views.UserPasswordChangeView.as_view(), name='password_change'),
    path('password_change/done/', views.UserPasswordChangeDoneView.as_view(), name='password_change_done'),
    path('password_reset/', views.UserPasswordResetView.as_view(), name='password_reset'),
    path('password_reset/done/', views.UserPasswordResetDoneView.as_view(), name='password_reset_done'),
    path('password_reset/<uidb64>/<token>/', views.UserPasswordResetConfirmView.as_view(), name='password_reset_confirm'),
    path('password_reset/complete/', views.UserPasswordResetCompleteView.as_view(), name='password_reset_complete'),
    path('register/', views.register, name='register'),
    path('account/edit/', views.edit_account, name='edit_account'),
]

weblog/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls', namespace='blog')),
]

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/forms.py
from django import forms
from .models import *


class PostForm(forms.ModelForm):
    image1 = forms.ImageField(label='تصویر اول')
    image2 = forms.ImageField(label='تصویر دوم')

    class Meta:
        model = Post
        fields = ['title', 'description', 'reading_time', 'category']
        widgets = {
            'title': forms.TextInput(attrs={'placeholder': 'عنوان'}),
            'description': forms.Textarea(attrs={'placeholder': 'توضیحات'}),
        }

    def clean_title(self):
        title = self.cleaned_data['title']
        if title:
            if len(title) < 5:
                raise forms.ValidationError('عنوان خیلی کوتاه هست.')
            else:
                return title

    def clean_description(self):
        description = self.cleaned_data['description']
        if description:
            if len(description) > 500:
                raise forms.ValidationError('توضیحات نباید بیشتر از 500 کاراکتر باشد.')
            else:
                return description


class TicketForm(forms.Form):
    SUBJECT_CHOICES = (
        ('پیشنهاد', 'پیشنهاد'),
        ('انتقاد', 'انتقاد'),
        ('گزارش', 'گزارش'),
    )
    message = forms.CharField(widget=forms.Textarea, required=True, label='پیام')
    name = forms.CharField(max_length=200, required=True, label='نام')
    email = forms.EmailField(required=True, label='ایمیل')
    phone = forms.CharField(max_length=11, required=True, label='شماره تماس')
    subject = forms.ChoiceField(choices=SUBJECT_CHOICES, label='موضوع')

    def clean_phone(self):
        phone = self.cleaned_data['phone']
        if phone:
            if not phone.isnumeric():
                raise forms.ValidationError('شماره تلفن عددی نیست')
            else:
                return phone


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'body']
        widgets = {
            'name': forms.TextInput(attrs={'placeholder': 'نام'}),
            'body': forms.Textarea(attrs={'placeholder': 'متن کامنت'})
        }

    def clean_name(self):
        name = self.cleaned_data['name']
        if name:
            if len(name) < 3:
                raise forms.ValidationError('نام کوتاه هست.')
            else:
                return name

    def clean_body(self):
        body = self.cleaned_data['body']
        if body:
            if len(body) > 300:
                raise forms.ValidationError('متن کامنت بیش ازحد مجاز است.')
            else:
                return body


class SearchForm(forms.Form):
    query = forms.CharField()


# class LoginForm(forms.Form):
#     username = forms.CharField(max_length=200, required=True)
#     password = forms.CharField(max_length=200, required=True, widget=forms.PasswordInput)


class UserRegisterForm(forms.ModelForm):
    password = forms.CharField(max_length=20, widget=forms.PasswordInput, label='پسورد')
    password2 = forms.CharField(max_length=20, widget=forms.PasswordInput, label='تکرار پسورد')

    class Meta:
        model = User
        fields = ['username', 'first_name', 'last_name', 'email']

    def clean_password2(self):
        cd = self.cleaned_data
        if cd['password'] != cd['password2']:
            raise forms.ValidationError('پسوردها مطابقت ندارند')
        return cd['password2']


class UserEditForm(forms.ModelForm):
    class Meta:
        model = User
        fields = ['first_name', 'last_name', 'email']


class AccountEditForm(forms.ModelForm):
    class Meta:
        model = Account
        fields = ['date_of_birth', 'bio', 'job', 'photo']

blog/views.py
from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from blog.models import *
from blog.forms import *
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.views.decorators.http import require_POST
from django.db.models import Q
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank, TrigramSimilarity
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import *


def index(request):
    return render(request, 'blog/index.html')


def post_list(request, category=None):
    if category is not None:
        posts = Post.published.filter(category=category)
    else:
        posts = Post.published.all()
    paginator = Paginator(posts, 2)
    page_number = request.GET.get('page', 1)
    try:
        posts = paginator.page(page_number)
    except EmptyPage:
        posts = paginator.page(paginator.num_pages)
    except PageNotAnInteger:
        posts = paginator.page(1)
    context = {
        'posts': posts,
        'category': category,
    }
    return render(request, 'blog/list.html', context)


def post_detail(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    form = CommentForm()
    comments = post.comments.filter(active=True)
    context = {
        'post': post,
        'form': form,
        'comments': comments,
    }
    return render(request, 'blog/detail.html', context)


def ticket(request):
    if request.method == "POST":
        form = TicketForm(request.POST)
        if form.is_valid():
            cd = form.cleaned_data
            Ticket.objects.create(message=cd['message'], name=cd['name'], email=cd['email'], phone=cd['phone'],
                                  subject=cd['subject'])
            return redirect('blog:index')
    else:
        form = TicketForm()
    return render(request, 'forms/ticket.html', {'form': form})


@require_POST
def post_comment(request, post_id):
    post = get_object_or_404(Post, id=post_id, status=Post.Status.PUBLISHED)
    comment = None
    form = CommentForm(request.POST)
    if form.is_valid():
        comment = form.save(commit=False)
        comment.post = post
        comment.save()
    context = {'post': post, 'comment': comment, 'form': form}
    return render(request, 'forms/comment.html', context)


@login_required
def post_create(request):
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(post=post, image_file=form.cleaned_data['image1'])
            Image.objects.create(post=post, image_file=form.cleaned_data['image2'])
            return redirect('blog:profile')
    else:
        form = PostForm()
    context = {'form': form}
    return render(request, 'forms/post.html', context)


# def post_search(request):
#     query = None
#     results = []
#     if 'query' in request.GET:
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             results1 = Post.published.filter(title__icontains=query)
#             results2 = Post.published.filter(description__icontains=query)
#             results = results1 | results2
#     context = {'query': query, 'results': results}
#     return render(request, 'blog/search.html', context)


# def post_search(request):
#     query = None
#     results = []
#     if 'query' in request.GET:
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             results = Post.published.filter(Q(title__icontains=query) | Q(description__icontains=query))
#     context = {'query': query, 'results': results}
#     return render(request, 'blog/search.html', context)


# def post_search(request):
#     query = None
#     results = []
#     if 'query' in request.GET:
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             results = Post.published.filter(Q(title__search=query) | Q(description__search=query))
#     context = {'query': query, 'results': results}
#     return render(request, 'blog/search.html', context)


# def post_search(request):
#     query = None
#     results = []
#     if 'query' in request.GET:
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             results = Post.published.annotate(search=SearchVector('title', 'description','slug')).filter(search=query)
#     context = {'query': query, 'results': results}
#     return render(request, 'blog/search.html', context)


# def post_search(request):
#     query = None
#     results = []
#     if 'query' in request.GET:
#         form = SearchForm(request.GET)
#         if form.is_valid():
#             query = form.cleaned_data['query']
#             search_query = SearchQuery(query)
#             search_vector = SearchVector('title', 'description', 'slug')
#             # search_vector = SearchVector('title', weight='A') + SearchVector('description', weight='B') + SearchVector('slug', 'C')
#             search_rank = SearchRank(search_vector, search_query)
#             results = Post.published.annotate(search=search_vector, rank=search_rank).filter(search=search_query).order_by('-rank')
#             # results = Post.published.annotate(search=search_vector, rank=search_rank).filter(rank__gte=0.3).order_by('-rank')
#     context = {'query': query, 'results': results}
#     return render(request, 'blog/search.html', context)

def post_search(request):
    query = None
    post_results = []
    image_results = []
    if 'query' in request.GET:
        form = SearchForm(request.GET)
        if form.is_valid():
            query = form.cleaned_data['query']
            trigram_similarity1 = TrigramSimilarity('title', query)
            trigram_similarity2 = TrigramSimilarity('description', query)
            trigram_similarity3 = TrigramSimilarity('title', query)
            trigram_similarity4 = TrigramSimilarity('description', query)
            post_results1 = Post.published.annotate(similarity=trigram_similarity1).filter(similarity__gt=0.1)
            post_results2 = Post.published.annotate(similarity=trigram_similarity2).filter(similarity__gt=0.1)
            image_results1 = Image.objects.annotate(similarity=trigram_similarity3).filter(similarity__gt=0.1)
            image_results2 = Image.objects.annotate(similarity=trigram_similarity4).filter(similarity__gt=0.1)
            post_results = list(post_results1) + list(post_results2)
            image_results = list(image_results1) + list(image_results2)
            post_results.sort(key=lambda x: x.similarity, reverse=True)
            image_results.sort(key=lambda x: x.similarity, reverse=True)

    context = {'query': query, 'post_results': post_results, 'image_results': image_results}
    return render(request, 'blog/search.html', context)


@login_required
def profile(request):
    user = request.user
    posts = Post.published.filter(author=user)
    context = {'posts': posts, 'user': user}
    return render(request, 'blog/profile.html', context)


@login_required
def post_delete(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        post.delete()
        return redirect('blog:profile')
    return render(request, 'forms/post_delete.html', {'post': post})


@login_required
def post_edit(request, post_id):
    post = get_object_or_404(Post, id=post_id)
    if request.method == 'POST':
        form = PostForm(request.POST, request.FILES, instance=post)
        if form.is_valid():
            post = form.save(commit=False)
            post.author = request.user
            post.save()
            Image.objects.create(image_file=form.cleaned_data['image1'], post=post)
            Image.objects.create(image_file=form.cleaned_data['image2'], post=post)
            return redirect('blog:profile')
    else:
        form = PostForm(instance=post)
    context = {'form': form, 'post': post}
    return render(request, 'forms/post.html', context)


@login_required
def image_delete(request, image_id):
    image = get_object_or_404(Image, id=image_id)
    image.delete()
    return redirect('blog:profile')


# def user_login(request):
#     if request.method == 'POST':
#         form = LoginForm(request.POST)
#         if form.is_valid():
#             cd = form.cleaned_data
#             user = authenticate(request, username=cd['username'], password=cd['password'])
#             if user is not None:
#                 if user.is_active:
#                     login(request, user)
#                     return redirect('blog:profile')
#                 else:
#                     return HttpResponse('your account is disabled')
#             else:
#                 return HttpResponse('you are not logged in')
#     else:
#         form = LoginForm()
#     return render(request, 'forms/login.html', {'form': form})


# def logout_view(request):
#     logout(request)
#     return redirect(request.META.get('HTTP_REFERER'))


class UserPasswordChangeView(PasswordChangeView):
    template_name = 'registration/password_change_form.html'
    success_url = reverse_lazy('blog:password_change_done')


class UserPasswordChangeDoneView(PasswordChangeDoneView):
    template_name = 'registration/password_change_done.html'


class UserPasswordResetView(PasswordResetView):
    template_name = 'registration/password_reset_form.html'
    success_url = reverse_lazy('blog:password_reset_done')
    email_template_name = 'registration/password_reset_email.html'


class UserPasswordResetDoneView(PasswordResetDoneView):

blog/templates/blog/detail.html
{% extends 'parent/base.html' %}
{% load jformat %}
{% load blog_tags %}

{% block title %}post detail{% endblock %}


{% block content %}
    <h1 class="post-detail">{{ post.title }}</h1>
    <p class="author">author: {{ post.author }}</p>
    <span class="pub-date">{{ post.publish|jformat:"%Y/%m/%d-%H:%M" }}</span>
    <div>
        {% for img in post.images.all %}
            {% if forloop.counter <= 2 %}
                <img src="{{ img.image_file.url }}" alt="{{ img.title }}">
            {% endif %}
        {% endfor %}
    </div>
    <div class="des"><p class="des-p">{{ post.description|replace_names_with_asterisk|markdown }}</p></div>
    <div>
        {% for img in post.images.all %}
            {% if forloop.counter > 2 %}
                <img src="{{ img.image_file.url }}" alt="{{ img.title }}">
            {% endif %}
        {% endfor %}
    </div>
    <hr>

    {% with comments.count as cm_count %}
        <div>{{ cm_count }} comment{{ cm_count|pluralize }}</div><br>
        <div>
            {% for comment in comments %}
                <hr>
                <br>{{ comment.name }}<br>
                <br>{{ comment.body|linebreaks }}<br>
                <hr>
            {% empty %}
                <p>هیچ کامنتی وجود ندارد.</p><br>
            {% endfor %}
        </div>
    {% endwith %}
    <br><br>
    <form action="{% url 'blog:post_comment' post.id %}" method="post" novalidate>
        {% csrf_token %}
        <div>
            {{ form.name.label_tag }}
            {{ form.name }}
            {{ form.name.errors }}<br><br>
        </div>
        <div>
            {{ form.body.label_tag }}
            {{ form.body }}
            {{ form.body.errors }}<br><br>
        </div>
        <input type="submit" value="افزودن کامنت"><br><br>
    </form>
{% endblock %}

blog/templates/blog/index.html
{% extends 'parent/base.html' %}
{% load blog_tags %}

{% block title %} Home Page {% endblock %}

{% block content %}
    <h2>آمار</h2>
    <p>تعداد پست: {% total_posts %}</p>
    <p>تعداد کامنت: {% total_comments %}</p>
    <p>تاریخ اخرین پست: {% last_post_date %}</p>

    {% latest_posts 10 %}

    <h2>پست (بیشتر زمان مطالعه)</h2>
    {% most_study_time %}

    <h2>پست (کمترین زمان مطالعه)</h2>
    {% minimum_study_time %}

    <h2>فعال ترین کاربر ها</h2>
    {% most_active_users 10 as act_users %}
    {% for user in act_users %}
    	<p>{{ user.username }}: with {{ user.users_count }} posts</p>
    {% endfor %}


    <h2>محبوب ترین پست ها</h2>
    {% most_popular_posts 10 as pop_posts %}
    {% for post in pop_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}" style="text-decoration: none; color: black;">
                {{ post.title }}: with {{ post.comments_count }} comments
            </a>
        </p><br>
    {% endfor %}

{% endblock %}

blog/templates/blog/list.html
{% extends 'parent/base.html' %}


{% block title %}post list{% endblock %}


{% block content %}
    {% if category %}
        <h1 class="post-list"><a href="{% url 'blog:post_list' %}">لیست پست ها {{ category }}</a></h1>
    {% else %}
        <h1 class="post-list"><a href="{% url 'blog:post_list' %}">لیست پست ها</a></h1>
    {% endif %}

    <div>
        <a href="{% url 'blog:post_list_category' 'هوش مصنوعی' %}">هوش مصنوعی</a>
    </div>
    <div>
        <a href="{% url 'blog:post_list_category' 'برنامه نویسی' %}">برنامه نویسی</a>
    </div>
    <div>
        <a href="{% url 'blog:post_list_category' 'بلاکچین' %}">بلاکچین</a>
    </div>
    <div>
        <a href="{% url 'blog:post_list_category' 'امنیت' %}">امنیت</a>
    </div>
    <div>
        <a href="{% url 'blog:post_list_category' 'سایر' %}">سایر</a>
    </div>

    <ol style="--length: {{ posts|length }}" role="list">
        {% for post in posts %}
            <li style="--i: {{ forloop.counter }}">
                <h3 class="post-title">
                    <a style="text-decoration: none; color: black;" href="{{ post.get_absolute_url }}">
                        {{ post.title }}
                    </a>
                </h3>
                <p class="descr">{{ post.description|truncatewords:5 }}</p>
                <img src="{{ post.images.first.image_file.url }}" alt="{{ post.images.first.title }}">
            </li>
        {% endfor %}
    </ol>
    {% include 'partials/pagination.html' with page=posts %}
{% endblock %}

blog/templates/blog/profile.html
{% extends 'parent/base.html' %}

{% block title %} Profile | {{ user }} {% endblock %}


{% block content %}
    <p><a href="{% url 'blog:post_create' %}">ایجاد پست</a></p>
    <table style="width: 80%; border: 2px solid black; text-align: center; direction: rtl;">
        <tr>
            <th>ردیف</th>
            <th>مشاهده</th>
            <th>ویرایش</th>
            <th>حذف</th>
        </tr>
        {% for post in posts %}
            <tr>
                <td>{{ forloop.counter }}</td>
                <td><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></td>
                <td><a href="{% url 'blog:post_edit' post.id %}">ویرایش</a></td>
                <td><a href="{% url 'blog:post_delete' post.id %}">حذف</a></td>
            </tr>
        {% endfor %}
    </table>
    <a href="{% url 'blog:logout' %}">خروج</a><br>
    <a href="{% url 'blog:password_change' %}">تغییر پسورد</a><br>
    <a href="{% url 'blog:edit_account' %}">تغییر اطلاعات شخصی</a>
{% endblock %}

blog/templates/blog/search.html
{% extends 'parent/base.html' %}

{% block title %}post search{% endblock %}


{% block content %}
    {% if query %}
        <span>{{ post_results|length }}:</span> <span>نتایج جستجو برای {{ query }}</span><br>
        <span>{{ image_results|length }}:</span> <span>نتایج جستجو برای {{ query }}</span>
    {% endif %}

    <h2>نتایج پست‌ها</h2>
    {% for post in post_results %}
        <div>
            <hr>
            <p><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></p>
            <p>{{ post.description|linebreaks }}</p>
            <hr>
        </div>
    {% empty %}
        <p>هیچ نتیجه ای یافت نشد...</p>
    {% endfor %}

    <h2>نتایج تصاویر</h2>
    {% for image in image_results %}
        <div>
            <hr>
            <p><a href="{{ image.post.get_absolute_url }}">{{ image.title }}</a></p>
            <p>{{ image.description|linebreaks }}</p>
            <hr>
        </div>
    {% empty %}
        <p>هیچ نتیجه ای یافت نشد...</p>
    {% endfor %}


{% endblock %}